import type { Hotel, Room } from "@/types";

export const ROOMS: Room[]  = [
  {
    id: "rm_001",
    name: "Park View Suite",
    guests: 3,
    bed: "1 King + Sofa",
    size: "55 m²",
    pricePerNight: 680000,
    currency: "NGN",
    status: "Available",
    amenities: ["Park View", "Free WiFi", "Air Conditioning"],
  },
  {
    id: "rm_002",
    name: "Deluxe City Room",
    guests: 2,
    bed: "1 Queen",
    size: "40 m²",
    pricePerNight: 420000,
    currency: "NGN",
    status: "Available",
    amenities: ["City View", "Workspace", "Smart TV"],
  },
  {
    id: "rm_003",
    name: "Executive Suite",
    guests: 4,
    bed: "1 King + Sofa",
    size: "65 m²",
    pricePerNight: 890000,
    currency: "NGN",
    status: "Booked",
    amenities: ["Lounge Access", "Mini Bar", "Balcony"],
  },
  {
    id: "rm_004",
    name: "Standard Room",
    guests: 2,
    bed: "2 Twin Beds",
    size: "30 m²",
    pricePerNight: 250000,
    currency: "NGN",
    status: "Maintenance",
    amenities: ["Free WiFi", "TV"],
  },
] as const;

export const HOTELS: Hotel[] = [
  {
    id: "htl_001",
    name: "Azure Bay Hotel",
    location: "Victoria Island, Lagos",
    rating: 4.6,
    reviews: 124,
    pricePerNight: 45000,
    currency: "NGN",
    image: "/hotels/hotel1.webp",
    amenities: ["Free WiFi", "Pool", "Gym", "Restaurant"],
    isFeatured: true,
    status: "Operational",
    phoneNumber: 9053727890,
    rooms: ROOMS,
    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
  {
    id: "htl_002",
    name: "Palm View Resort",
    location: "Lekki, Lagos",
    rating: 4.3,
    reviews: 98,
    pricePerNight: 38000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Breakfast", "Free Parking", "Sea View"],
    isFeatured: false,
    status: "Closed",
    phoneNumber: 9053727890,
    rooms: ROOMS,

    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
  {
    id: "htl_003",
    name: "The Grand Orchid",
    location: "GRA, Port Harcourt",
    rating: 4.8,
    reviews: 210,
    pricePerNight: 60000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Spa", "Pool", "Bar", "Airport Shuttle"],
    isFeatured: true,
    status: "Operational",
    phoneNumber: 9053727890,
    rooms: ROOMS,

    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
  {
    id: "htl_004",
    name: "Sunset Haven Suites",
    location: "Ibadan, Oyo",
    rating: 4.1,
    reviews: 67,
    pricePerNight: 25000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Free WiFi", "Restaurant"],
    isFeatured: false,
    status: "Operational",
    phoneNumber: 9053727890,
    rooms: ROOMS,

    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
  {
    id: "htl_005",
    name: "Emerald Crown Hotel",
    location: "Abuja, FCT",
    rating: 4.7,
    reviews: 156,
    pricePerNight: 52000,
    currency: "NGN",
    image: "/hotels/hotel1.webp",
    amenities: ["Gym", "Conference Hall", "Pool"],
    isFeatured: true,
    status: "Renovation",
    phoneNumber: 9053727890,
    rooms: ROOMS,

    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
  {
    id: "htl_006",
    name: "Royal Crest Inn",
    location: "Abeokuta, Ogun",
    rating: 4.0,
    reviews: 45,
    pricePerNight: 22000,
    currency: "NGN",
    image: "/hotels/hotel1.webp",
    amenities: ["Free Parking", "WiFi"],
    isFeatured: false,
    status: "Operational",
    phoneNumber: 9053727890,
    rooms: ROOMS,

    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
  {
    id: "htl_007",
    name: "Lagoon Pearl Hotel",
    location: "Ikoyi, Lagos",
    rating: 4.9,
    reviews: 320,
    pricePerNight: 75000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Spa", "Pool", "Fine Dining", "Gym"],
    isFeatured: true,
    status: "Operational",
    phoneNumber: 9053727890,
    rooms: ROOMS,

    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
  {
    id: "htl_008",
    name: "Hilltop Comfort Lodge",
    location: "Ado-Ekiti, Ekiti",
    rating: 3.9,
    reviews: 38,
    pricePerNight: 18000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Breakfast", "Free WiFi"],
    isFeatured: false,
    status: "Operational",
    phoneNumber: 9053727890,
    rooms: ROOMS,

    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
  {
    id: "htl_009",
    name: "Ocean Breeze Hotel",
    location: "Uyo, Akwa Ibom",
    rating: 4.4,
    reviews: 89,
    pricePerNight: 34000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Sea View", "Restaurant", "Bar"],
    isFeatured: false,
    status: "Operational",
    phoneNumber: 9053727890,
    rooms: ROOMS,

    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
  {
    id: "htl_010",
    name: "Golden Palm Suites",
    location: "Asaba, Delta",
    rating: 4.2,
    reviews: 72,
    pricePerNight: 29000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Pool", "Gym", "Free Parking"],
    isFeatured: false,
    status: "Renovation",
    phoneNumber: 9053727890,
    rooms: ROOMS,
    description:
      "Experience Venetian elegance in our restored 15th-century palazzo overlooking the Grand Canal. Features original frescoes, Murano glass chandeliers, and private water taxi service.",
  },
] as const;
