
export const HOTELS = [
  {
    id: "htl_001",
    name: "Azure Bay Hotel",
    location: "Victoria Island, Lagos",
    rating: 4.6,
    reviews: 124,
    pricePerNight: 45000,
    currency: "NGN",
    image: "/hotels/hotel1.webp",
    amenities: ["Free WiFi", "Pool", "Gym", "Restaurant"],
    isFeatured: true,
    status: "Operational",
  },
  {
    id: "htl_002",
    name: "Palm View Resort",
    location: "Lekki, Lagos",
    rating: 4.3,
    reviews: 98,
    pricePerNight: 38000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Breakfast", "Free Parking", "Sea View"],
    isFeatured: false,
    status: "Closed",
  },
  {
    id: "htl_003",
    name: "The Grand Orchid",
    location: "GRA, Port Harcourt",
    rating: 4.8,
    reviews: 210,
    pricePerNight: 60000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Spa", "Pool", "Bar", "Airport Shuttle"],
    isFeatured: true,
    status: "Operational",
  },
  {
    id: "htl_004",
    name: "Sunset Haven Suites",
    location: "Ibadan, Oyo",
    rating: 4.1,
    reviews: 67,
    pricePerNight: 25000,
    currency: "NGN",
    image: "/hotels/hotel2.webp",
    amenities: ["Free WiFi", "Restaurant"],
    isFeatured: false,
    status: "Operational",
  },
  {
    id: "htl_005",
    name: "Emerald Crown Hotel",
    location: "Abuja, FCT",
    rating: 4.7,
    reviews: 156,
    pricePerNight: 52000,
    currency: "NGN",
    image: "/hotels/hotel1.webp",
    amenities: ["Gym", "Conference Hall", "Pool"],
    isFeatured: true,
    status: "Renovation",
  },
] as const;
