import type { Room } from "@/types";

export const ROOMS: Room[] = [
  {
    id: "rm_001",
    name: "Park View Suite",
    guests: 3,
    bed: "1 King + Sofa",
    size: "55 m²",
    pricePerNight: 680000,
    currency: "NGN",
    status: "Available",
    amenities: ["Park View", "Free WiFi", "Air Conditioning"],
  },
  {
    id: "rm_002",
    name: "Deluxe City Room",
    guests: 2,
    bed: "1 Queen",
    size: "40 m²",
    pricePerNight: 420000,
    currency: "NGN",
    status: "Available",
    amenities: ["City View", "Workspace", "Smart TV"],
  },
  {
    id: "rm_003",
    name: "Executive Suite",
    guests: 4,
    bed: "1 King + Sofa",
    size: "65 m²",
    pricePerNight: 890000,
    currency: "NGN",
    status: "Booked",
    amenities: ["Lounge Access", "Mini Bar", "Balcony"],
  },
  {
    id: "rm_004",
    name: "Standard Room",
    guests: 2,
    bed: "2 Twin Beds",
    size: "30 m²",
    pricePerNight: 250000,
    currency: "NGN",
    status: "Maintenance",
    amenities: ["Free WiFi", "TV"],
  },
] as const;

export const BOOKINGS = [
  {
    bookingId: "BK-001",
    guestName: "John Doe",
    guestEmail: "john.doe@email.com",
    hotel: "Sunset Hotel",
    room: "Deluxe Room",
    duration: "3 nights",
    status: "Confirmed",
    amount: "NGN30,000",
  },
  {
    bookingId: "BK-002",
    guestName: "Sarah Williams",
    guestEmail: "sarah.w@email.com",
    hotel: "Ocean View Resort ",
    room: "Deluxe Room",

    duration: "2 nights",
    status: "Confirmed",
    amount: "NGN130,000",
  },
  {
    bookingId: "BK-003",
    guestName: "Michael Brown",
    guestEmail: "michael.b@email.com",
    hotel: "Grand Palace Hotel",
    room: "Deluxe Room",

    duration: "5 nights",
    status: "Pending",
    amount: "NGN50,000",
  },
  {
    bookingId: "BK-004",
    guestName: "Amina Yusuf",
    guestEmail: "amina.y@email.com",
    room: "Deluxe Room",

    hotel: "City Lights Inn ",
    duration: "1 night",
    status: "Confirmed",
    amount: "NGN30,000",
  },
  {
    bookingId: "BK-005",
    guestName: "David Okoye",
    guestEmail: "david.o@email.com",
    hotel: "Palm Breeze Hotel ",
    room: "Deluxe Room",

    duration: "4 nights",
    status: "Cancelled",
    amount: "NGN30,000",
  },
];
